### PR TITLE
Adding MVL staking provider

### PR DESCRIPTION
**Pull request by picardcapt1212**
Hello Team!
This is a PR for adding mvlStaking provider on ethereum, bsc network.

### CODE REVIEW

**Comment by picardcapt1212** [comment]
Yes thats right. Thanks for reply.

**Review by mantasfam — APPROVED** [review]

**Comment by mantasfam** [comment]
If you want your token mapped with a dapp, you should add token addresses in developers' dashboard: https://dappradar.com/dashboard/dapps/47405

**Comment by mantasfam** [comment]
It should be visible soon. 
I didn't see any ETH token. MVL in Ethereum and wMVL (or similar) in BSC.

**Comment by picardcapt1212** [comment]
```
const TOKEN_ADDRESSES = [
  '0xA849EaaE994fb86Afa73382e9Bd88c2B6b18Dc71',
  '0x3c8ad34155b83ddb7f43119a19503d34ed2b5c7a',
];
```
Oh I wrote single and lp token address.
For ethereum provider, I am using these token address. The first one is MVL and the other one is LP(MVL, ETH UniV2 token),
And also bsc provider is bMVL and LP token.

**Comment by mantasfam** [comment]
If you have any feedback on defi integration process we would be happy to hear that :)

**Pull request merged**
