### PR TITLE
squadswap & squadswapv3 multichain integration

### PR DESCRIPTION
**Pull request by zxselimcan**

### CODE REVIEW

**Comment by zxselimcan** [comment]
can anybody check it?

**Comment by mantasfam** [comment]
Hello. You integrated squadswap and squadswap V3 as two separate dapps, but in Dappradar there is only one dapp submitted: https://dappradar.com/dapp/squadswap

Are you going to submit another dapp for squadswap V3? If no, then these calculation should be merged into one file

**Comment by zxselimcan** [comment]
Thanks for the answer. I'm going to make it like pancakeswap's one. It looks like my answer is yes.

**Comment by zxselimcan** [comment]
Thanks for accepting. I just try to stick to the instructions given to me.

**Comment by mantasfam** [comment]
Gm. How is going, are you going to merge these integrations or submit squadswapv3 dapp to DappRadar?

**Comment by zxselimcan** [comment]
Hi @mantasfam , is submitting squadswapv3 dapp to DappRadar needs additional process? If it requires it, I can focus on the merge. Otherwise, let's submit the current code.

**Comment by mantasfam** [comment]
> Hi @mantasfam , is submitting squadswapv3 dapp to DappRadar needs additional process? If it requires it, I can focus on the merge. Otherwise, let's submit the current code.

Yes, it required a separate dapp submission. I had an internal discussion with a team and we decided there is no point in submitting another dapp, as most data would be duplicated between dapps. So we prefer that you merge providers in this PR instead

**Comment by zxselimcan** [comment]
i have no idea how to merge them. is there any example? can i return like `export const { tvl, tvlv3 }` or how?

**Comment by mantasfam** [comment]
Check https://github.com/dappradar/defi-providers/blob/master/src/factory/providers/arbitrum/camelot/index.ts

**Comment by zxselimcan** [comment]
done @mantasfam can you check it please

**Review by mantasfam — APPROVED** [review]
Looks good

**Comment by zxselimcan** [comment]
ser, could you check it: https://github.com/dappradar/defi-providers/pull/316

**Comment by zxselimcan** [comment]
> ser, could you check it: #316

@mantasfam

**Pull request merged**
