### PR TITLE
Integrate Newrl RWA protocol

### PR DESCRIPTION
**Pull request by kousthubraja**
This PR is for integrating Newrl Real World Assets lending protocol with DappRadar. 

As the commodity tokens locked inside the protocol are not separately listed on CoinGecko or other CeX, the approach used to calculate the TVL is as follows. RWA refers to Real World Asset token.

1. Get the locked RWA tokens in the protocol form the chain.
2. Use UniswapV3 DeX for getting Last Traded Price of the RWA token in USDC stable coin.
3. Return the summed balances in USDC.

### CODE REVIEW

**Comment by mantasfam** [comment]
Hi. I can find this dapp in Dappradar dapps. If it's not submitted yet, you can do it here: https://dappradar.com/dashboard/submit-dapp
After dapp is submitted I will map this TVL integration to it.

**Comment by kousthubraja** [comment]
> Hi. I can find this dapp in Dappradar dapps. If it's not submitted yet, you can do it here: https://dappradar.com/dashboard/submit-dapp After dapp is submitted I will map this TVL integration to it.

Hi, already submitted it. 
https://dappradar.com/dashboard/dapps/48403

**Comment by kousthubraja** [comment]
Hi @mantasfam Thanks for approving the dapp. The TVL shows as expected now.

**Review by mantasfam — APPROVED** [review]

**Comment by mantasfam** [comment]
If you have any feedback on defi integration process we would be happy to hear that :)

**Pull request merged**
