### PR TITLE
zkSync Era Increment Protocol Integration

### PR DESCRIPTION
**Pull request by webthethird**
Add TVL provider for Increment Protocol.

### CODE REVIEW

**Comment by mantasfam** [comment]
Hello, 
This is integration of this dapp right?
https://dappradar.com/dapp/increment

**Comment by webthethird** [comment]
> Hello, This is integration of this dapp right? https://dappradar.com/dapp/increment

Correct

**Comment by mantasfam** [comment]
Hey. I think calculated TVL is too high:
`{
  '0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4': '86482359761640234676586'
}`

It equals to $86,568,842,121,401,874.91. And expected is $86k?

I think USDC balance have to be shifted by 10^12

**Comment by webthethird** [comment]
> Hey. I think calculated TVL is too high: `{ '0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4': '86482359761640234676586' }`
> 
> It equals to $86,568,842,121,401,874.91. And expected is $86k?
> 
> I think USDC balance have to be shifted by 10^12

Thanks for catching this! I just committed the fix.

**Review by mantasfam — APPROVED** [review]

**Comment by mantasfam** [comment]
Approved. 

If you have any feedback on defi integration process we would be happy to hear that!

**Comment by mantasfam** [comment]
Hello. Volume is calculated automatically from contracts that are mapped with a dapp in the developers dashboard.

**Comment by louie-ml** [comment]
Hi @mantasfam another smart contract has been added to developers dashboard called Perpetual. Perhaps this can help fix the volume.

Nevertheless, based on the data queried from Dune, the volume should be higher than what is displayed on dapp radar, please advise, many thanks!
image

**Pull request merged**
